image: elixir:1.2.4

services:
  - postgres:9.5

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix compile
  - mix ecto.migrate

stages:
  - test

test:
  script:
    - GIT_BRANCH=$CI_BUILD_REF_NAME mix test

variables:
  MIX_ENV: test
  DATABASE_URL: postgres://postgres@postgres/postgres
